### ISSUE TITLE
cologne symlink to apidev

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-apidev#1]
Currently, on Cologne server, the location of the csl-apidev repository is 'scans/awork/apidev'.

This is awkward for a couple of reasons.

As a tentative first step towards reducing the awkwardnesses, I've made a symlink on Cologne server in the 'scans' directory from 'csl-apidev' to 'awork/apidev'.

`ln -s csl-apidev awork/apidev`

### simple-search access via symlink directory
`https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/simple-search/v1.0/list-0.2s.html`
seems to work just fine, and also the current
`https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/simple-search/v1.0/list-0.2s.html`
works fine.

### Cologne repository maintenance via symlink
When connected by ssh, one can `cd scans/csl-apidev`.  Then one can edit and otherwise manipulate the files in the repository.

### readlink 
To find the target of the symlink,
```
> cd scans
> readlink -f csl-apidev
/afs/rrz.uni-koeln.de/vol/www/projekt/sanskrit-lexicon/http/docs/scans/awork/apidev
```

**Comment by funderburkjim** [comment]
### Need for dokuwiki work

There is some apidev code  (e.g., that involving 'dictinfowhich') which adjusts file locations depending on when the code is running on the Cologne server or on an XAMPP or Ubuntu server.

There is also a dependency of some apidev code on csl-websanlexicon code, and the method of keeping the two code bases in sync is currently a manual process which makes an assumption about the relative locations of the repositories.   In fact, it is the awkwardness of this syncing that I noticed today and that prompted me to  introduce this issue.

Before proceeding further with rationalizing the location of the apidev repository, one thing that is needed is a description of some of the apidev code.  I'll attend to this in coming days, probably on the dokuwiki, and then return to this issue when the situation has been clarified.

**Comment by gasyoun** [comment]
> https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/simple-search/v1.0/list-0.2s.html

The URL is about 3 times longer, than should.

> https://www.sanskrit-lexicon.uni-koeln.de/s/

Would be the longest one we could need.

**Comment by drdhaval2785** [comment]
@funderburkjim I feel this item has been attended now. 
Marcis has been asking in all issues to have shorter and rather shortest URLs.

**Comment by funderburkjim** [comment]
The short-url item is addressed many other places.   This issue no longer needs to be open.
