### ISSUE TITLE
Remove www from /simple/

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-apidev#15]
There has been for some time a 'simple' url for simple-search.   [Here](https://github.com/sanskrit-lexicon/COLOGNE/issues/294) is a discussion of how that works on Cologne server.

Recently,  Marcis and I discussed this further in the context of some issue somewhere , and one of the suggestions was dropping the 'www.' prefix.

For example,  https://www.sanskrit-lexicon.uni-koeln.de/simple/mw/danda/iast/no   works,
but what about the shorter https://sanskrit-lexicon.uni-koeln.de/simple/mw/danda/iast/no   [no www.]?

Well, now the shorter form seems to work!

Next two comments discuss technical details of changes.

**Comment by funderburkjim** [comment]
## Allow no www in primary domain

Previously, https://sanskrit-lexicon.uni-koeln.de    generated an error message from the server:
`Your connection is not private`
The Webmaster (Patrick) was able to do something that fixed this.

**Comment by funderburkjim** [comment]
## Using relative urls
The next problem was that CORS (Cross-origin) problems occurred when resolving a url such as
 https://sanskrit-lexicon.uni-koeln.de/simple/mw/go .

The solution here required a changed to [list-0.2s_rw.php
](https://github.com/sanskrit-lexicon/csl-apidev/blob/master/simple-search/v1.0/list-0.2s_rw.php),
which is the program that the .htacess rewrite rule calls.

Essentially, the change was to use relative urls, rather than urls with or without embedded 'www.' .
It seems that if the top-level url does not 'www.' prefix, and if the program run by the web page loads a resource that DOES use 'www.' prefix,  then the browser disallows the process to continue.

**Comment by funderburkjim** [comment]
## piwik still doesn't load

Using a non-www url such as https://sanskrit-lexicon.uni-koeln.de/simple/mw/go ,  everything visible to the user seems to work as expected.

However,  the usage-tracker 'piwik'  does not load (visible iin console in dev tools of browser).
Using a url WITH www  (https://www.sanskrit-lexicon.uni-koeln.de/simple/mw/go), however,  piwik.js does load.

Not sure what the problem is here.  It has lesser importance since the typical user does not see the error.

**Comment by funderburkjim** [comment]
@gasyoun   This 'www' issue came up in some recent GIthub issue,  but I can't seem to find that issue.
I do recall that you suggested another improvement in that issue comment.   Can you find the comment so I can address the other suggestion?

**Comment by gasyoun** [comment]
> Well, now the shorter form seems to work!

Hurray!

> Next two comments discuss technical details of changes.

Now we want to make sure there is only 1 URL of each kind. Every old-www to be redirected at server level no non-www.

> Essentially, the change was to use relative urls, rather than urls with or without embedded 'www.' .

Relative URLs the only way, right.

> Using a url WITH www (https://www.sanskrit-lexicon.uni-koeln.de/simple/mw/go), however, piwik.js does load.

That is soo strange, have to look at it myself.

`https://sanskrit-lexicon.uni-koeln.de/simple/mw/go` is good, but can we have `https://sanskrit-lexicon.uni-koeln.de/mw/go` ? That was the major suggestion, no need to have that `simple` word in URL if we keep 'em short.

**Comment by funderburkjim** [comment]
## piwik  and ad-blocker

The problem in dev console was 
`Failed to Load Resource net::ERR_BLOCKED_BY_CLIENT`.
A search for this error led to https://love2dev.com/blog/what-the-heck-does-neterr_blocked_by_client-mean-and-how-can-you-fix-it/ .    This article mentions that there are many potential causes.   One cause mentioned was the presence of ad-blocker extensions.   I do have an add blocker extension in Chrome.   When I disabled it for a display,   then, using the non-www url,  the  error message went away.

So consider the piwik part of this problem solved.

**Comment by gasyoun** [comment]
> presence of ad-blocker extensions

Oh, most of us have one, understood.

**Comment by drdhaval2785** [comment]
Closable?

**Comment by funderburkjim** [comment]
I think it is closable, and am closing
