### ISSUE TITLE
cleanup old files

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-apidev#2]
In beginning review of apidev,  I realize that the code has been developed over a long period (since about 2015) and that many of the files had some temporary use at some time, but are only in the way currently.

Thus, a first level housecleaning is in order.   Files definitely not of current interest will be deleted, such as those in 'old' subdirectories;  unused font files, etc.   Files which are not currently used but which nonetheless have some residual interest are not deleted.

I'll mention the deleted files in comments below.

**Comment by funderburkjim** [comment]
## deletions from top-level directory.

next.pdf, prev.pdf, siddhanta.ttf  (we have this in fonts subfolder),

*old* subfolder (50 files)

## deletions from css subfolder
*old* subfolder (5 files)

Note:  *css/csswork* folder is not used currently, but may have some interest as a study of the variations (ca 2015) among the css files of various dictionaries).

## deletions from fonts subfolder
We keep copies of the 4 web fonts also used present in csl-websanlexicon/v00/makotemplates/fonts/.   The 5 font files removed are:
Old Standard Indologique-Italic.otf  , Old Standard Indologique-Italic.ttf  , Old Standard Indologique-Regular.otf, praja.ttf, sanskrit2003.ttf

## deletions from htmlwork subfolder
This entire folder is not of current interest;  it represents a preliminary test of an earlier form of apidev which used dictionary databases of  partially precomputed html files for displays. 

However, this is still an interesting idea, so at this time we'll only delete the various code marked as 'old':
*old* subfolder of htmlwork (1 file),  
*htmlwork/makeassets/old* subfolder (1 file)

## no deletions from httpwork subfolder
Contains some preparations (2018) for switch of Cologne sanskrit-lexicon website to https.
Not of current use.

**Comment by funderburkjim** [comment]
## deletions from js subfolder
Delete js/old subfolder (3 files)

## no deletions from monier1list subfolder
There are 2 files;  not sure if they are part of any current work.

## deletions from mw_webtc1api
Delete all files in this directory. 

## deletions from mw72work
Deleted all 10 files in this directory.   These files are referenced only in two of the files of httpwork directory.

## deletions from *sample* subfolder
Delete *old* subfolder (6 files) and *old-20150817* subfolder (10 files).

## deletions from *simple-search* subfolder
delete *v1.0d/old* subfolder (18 files)
delete *v1.0/old* subfolder (18 files)
 
## deletions from *utilities* subfolder
Delete *old* subfolder (2 files)

**Comment by funderburkjim** [comment]
## summary
All in all, 168 files removed.

**Comment by gasyoun** [comment]
Clean and shiny. Hope we will get to short URLs short after.

**Comment by funderburkjim** [comment]
> short URLs   

when?   Not sure.  Sounds a reasonable idea from user perspective.  Not sure if it matters from programmer perspective.

**Comment by funderburkjim** [comment]
##  Delete a few more

dbg_apidev.txt   --   'dbgprint' function write-appends to this file, useful when debugging.  Not needed as part of repository.  It is in .gitignore.   

getword_prev.php  -- a prior version of getword.php.  No need to keep around

listview1.php -- self-described as a failed experiment of Feb 27, 2017

**Comment by funderburkjim** [comment]
## Delete a few more

httpwork/http_adjust_log.txt -- a log file of http changes.  No longer needed. It gets in the way of recursive grep searches (by showing many un-useful matches).

simple-search/v1.0/fetching.html, and simple-search/v1.0d/fetching.html -- used in early testing.

**Comment by gasyoun** [comment]
> Not sure if it matters from programmer perspective.

I'm sure it does not. But fits the API cleanup.

**Comment by funderburkjim** [comment]
## Delete a few more

sample/old directory  

sample/old-20150817 directory

These contain old versions of sample displays using apidev.
The sample directory itself contains revised versions.

sample/testmw-0.1.html  Uses an old php version for gathering data.

sample/easyspell_test.html  Uses an unavailable program apidev/easyspell.php

**Comment by funderburkjim** [comment]
## delete disphier.php
disphier.php just includes getword.php.  So is not needed.

disphier.php is only included by listview.php, so we change that to include getword.php.

in js/listview.js,  'disphier.php' is referenced;  change the reference to getword.php.

**Comment by funderburkjim** [comment]
## delete utilities/transcoder/old
This directory contains various transcoder files, which have no current interest.
