### ISSUE TITLE
.htaccess for simple search - oddities

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-apidev#20]
Here are the current Cologne rewrite rules:

```
RewriteRule simple/(.*$) scans/awork/apidev/simple-search/v1.0/list-0.2s_rw.php

RewriteRule simple$ scans/awork/apidev/simple-search/v1.0/list-0.2s_rw.php
```

There are still some oddities.
For example:  these also work
* https://sanskrit-lexicon.uni-koeln.de/verysimple
* https://sanskrit-lexicon.uni-koeln.de/blah/simple

It seems that 'simple can occur any where after the base url, rather than immediately after.

This seems undesireable to me, but I don't know how to change the rewrite rules.

Any experts out there?

**Comment by gasyoun** [comment]
> This seems undesireable to me

Must agree.

**Comment by funderburkjim** [comment]
After some fiddling,  the Cologne rewrite rules are now:
```
RewriteRule ^simple/(.*$) scans/awork/apidev/simple-search/v1.0/list-0.2s_rw.php
RewriteRule ^simple$ scans/awork/apidev/simple-search/v1.0/list-0.2s_rw.php
```

A '^' is now before 'simple' in each of the previous rules.

now:
* https://sanskrit-lexicon.uni-koeln.de/verysimple  fails  (404 - Document not found)
* https://sanskrit-lexicon.uni-koeln.de/blah/simple  fails  (Document not found)
* https://sanskrit-lexicon.uni-koeln.de/simple/   succeeds
* https://sanskrit-lexicon.uni-koeln.de/simple     succeeds
* https://sanskrit-lexicon.uni-koeln.de/simple/mw/guru  succeeds

This seems to solve the problem of this issue.

**Comment by gasyoun** [comment]
> This seems to solve the problem of this issue.

Hurray! Long live Jim.

> https://sanskrit-lexicon.uni-koeln.de/simple/mw/guru

works

but can we have

> https://sanskrit-lexicon.uni-koeln.de/s/mw/guru

Work as well? Just one more rule for me, please. Not instead, additional. 
And is there a way to link directly to some word? Not to simple, but to an exact ID?

**Comment by gasyoun** [comment]
Just like `/g/` in my Google has:
`https://groups.google.com/g/nagari`

It took 12 years for Google to understand how to shorten that URL to a single lettered `g`.
