### ISSUE TITLE
getsuggest.php gives two blank lines before JSON

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-apidev#25]
When I tried to make a call to getsuggest.php for creating an API , I got `\n\n` before the JSON output. This made the program think that it is a text output rather than JSON. 

Any reason or idea why these two blank lines are returned @funderburkjim ?

**Comment by funderburkjim** [comment]
I do not see those two blank lines.    

Try running this html program (fetch_suggest.html)
-- it shows that only an array is returned.
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>fetch_suggest</title>
</head>
<body>
<p id="result">
</p>
<script>
let url = 'https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/getsuggest.php?dict=mw&term=ap&input=iast';
fetch(url)
  .then(response => response.json())
  .then(data => {
  console.log('type of data = ',typeof(data));
  console.log('data=');
  console.log(data);
  let el = document.getElementById("result");
  let html = "<ul>\n";
  for(let i=0;i<data.length;i++) {
   let val = data[i];
   let html1 = `<li>data[${i}] = ${val}</li>\n`;
   html = html + html1;
  }
  html = html + "</ul>";
  el.innerHTML = html;
  }
  );
</script>
</body>
</html>
```

Result:

![image](https://user-images.githubusercontent.com/6393033/103106020-0b645080-4600-11eb-8db5-5d2dd6fae194.png)

**Comment by drdhaval2785** [comment]
HTML does not display newline character in some browsers. Kindly write the response to a txt file and check.

When I opened the link from the script in my chrome browser on mobile, it showed the following. There are definitely two blank lines there.

![Screenshot_20201225-080434_Chrome](https://user-images.githubusercontent.com/5755132/103115317-28dcfd00-4688-11eb-8bc1-5b953fe92b7a.jpg)

**Comment by funderburkjim** [comment]
## confirm
Am able to confirm that the string returned by getSuggest starts out with
`\n\n [`   (two line feeds and a space, then the square bracket).

Now trying to find where the first three characters `\n\n ` come from.

**Comment by funderburkjim** [comment]
## unwanted characters removed.

In one file (parm.php)  there was an extra space character at the end of file:
```
<?php
...
?>
 <<<< extra space
```
And in another file (dictinfo.php),  there were two blank lines after the `?>` at end of file.

These were the sneaky culprits.

php was adding these to the output stream.

Credit https://stackoverflow.com/questions/14145817/php-echo-adds-a-new-line
for suggestion.

**Comment by gasyoun** [comment]
> These were the sneaky culprits.

Hurray!
