### ISSUE TITLE
remove dalwhich and related

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-apidev#3]
## Background
In an earlier version of apidev,  some  dictionary digitization files used precomputed html versions instead of the xml.   The 'dalwhich.php' module had a function `dalwhich($dict)`  made a call 
to either 
* the Dal($dict) constructor (in dal.php), which accessed the html precomputed html, or  to
* the Dalraw($dict) constructor (in dalraw.php) which accessed the xml.

Later, the use of precomputed html was discontinued, and dalwhich.php was changed to always call the Dalraw($dict) constructor in dalraw.php.

We want to change names of things, as detailed in next comment.

**Comment by funderburkjim** [comment]
## Changes to apidev

* apidev's current dal.php is renamed to unused_dal.php -- later when I'm sure everything is properly changed,  this unused_dal.php program file can be deleted.
* dalraw.php is renamed to dal.php.  
  * The constructor in new dal.php is changed from Dalraw to Dal
  * instance variable *rawflag* removed -- it is always true.
* dalwhich.php is removed.
* references to dalwhich changed in getsuggest.php, getword.php, listhier.php, and servepdf.php
  * `require_once("dalwhich.php")`  changed to `require_once("dal.php")`
  * `$dal = dalwhich($dict)` changed to `$dal = newDal($dict)`
* remove references to `$dal->rawflag` in getword.php
* In basicadjust.php, change
  * `require_once('dalraw.php')` to `require_once("dal.php")`
  * `new Dalraw` to `new Dal`  (3 cases)

## Also change to csl-websanlexicon documentation
 basicadjust.php in csl-apidev is now identical to basicadjust.php in csl-websanlexicon.
     Change documentation (`csl-websanlexicon/readme_xampp.org` ) accordingly.

**Comment by funderburkjim** [comment]
## check apidev work.

simple-search uses the apidev code.  Seems to work ok. 👍 

Sync to github.

**Comment by gasyoun** [comment]
> simple-search

Where to look for it?

**Comment by funderburkjim** [comment]
Here is Github location of the simple-search-url:

https://github.com/sanskrit-lexicon/csl-apidev/blob/master/simple-search/v1.0/list-0.2s.html

Is that what you need?

**Comment by gasyoun** [comment]
> Here is Github location of the simple-search-url:

Thanks, yes, I want to see what the active equals for search are.
