### ISSUE TITLE
getsuggest bug: sura

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-apidev#30]
A user Zilton pointed out an error in the 'suggest' feature, such as with this display:
https://sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/sample/list-0.2.html

Assuming MW dictionary, (and assuming slp1 input), type 'sura' in citation field. You would see (before correction):
![image](https://user-images.githubusercontent.com/6393033/123005562-4fa09580-d384-11eb-8260-eb13621baf3a.png)

Note that the first word in the suggestions is 'surakta'.

But 'sura' IS a headword in MW, so why doesn't it appear in the suggestions?

The reason is that there are many compounds of 'su' whose spelling begins with 'sura',  and they occur in the 
dictionary order before the entry for 'sura'.  So 'sura', although a headword of MW, doesn't get in the list of words
starting with 'sura'!    

Solution:   If the given prefix (e.g. 'sura') occurs as a headword, be sure to put it at the top of the list of suggestions.

**Comment by funderburkjim** [comment]
After the correction:

![image](https://user-images.githubusercontent.com/6393033/123006699-136e3480-d386-11eb-811e-0d175737f228.png)

**Comment by funderburkjim** [comment]
The correction itself turned out to be a one-liner: https://github.com/sanskrit-lexicon/csl-apidev/commit/cd3509aa06ea69954b10338d8dbfe50c921b03be

**Comment by gasyoun** [comment]
An important one, have seen it before.
