### ISSUE TITLE
simple-search ap90 div bug

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-apidev#32]
Noticed a new bug with ap90 display at cologne server with simple-search.

![image](https://user-images.githubusercontent.com/6393033/197919951-73b8a2ba-461e-4fc6-adec-31e1841b1a15.png)

## localhost ok
The same search on local host displays properly.
![image](https://user-images.githubusercontent.com/6393033/197920173-43397cc1-a9b8-4d26-8033-7a86d0fcf53f.png)

Also, current basic display at cologne works properly.
An inspection of html shows no 'div' statements in the cologne-simple-search.

This may be somehow related to recent lrv dictionary work ([ref](https://github.com/sanskrit-lexicon/LRV/issues/15)).  I use ap90 simple-search at cologne often, and believe this discrepancy is recent.

Normally basicDisplay.php and basicAdjust.php in csl-apidev and in csl-websanlexicon are the same code.

**Comment by funderburkjim** [comment]
## problem may be with ap90.sqlite 

The ap90.xml entry is same:
```
<H1><h><key1>viSas</key1><key2>viSas</key2></h><body><s>viSas</s>  1 <ab>P.</ab> <div n="1"/><b>1</b> To cut up, kill; <ls>U. 4.</ls> <div n="1"/><b>2</b> To immolate, sacrifice.</body><tail><L>26527</L><pc>0994-b</pc></tail></H1>
```
and this agrees with the ap90.sqlite item.

But when retrieved from Cologne ap90.sqlite  (in dal.php), something else is being returned:
```
dal.php get_xml: sql=select * from ap90 where key='viSas' order by lnum
dal.php get_xml: rec[2]=   NEXT SHOULD BE SAME AS ap90.xml above, but is not!
<H1><h><key1>viSas</key1><key2>viSas</key2></h><body>1 P. <b>1</b> To cut up, kill; <lb/>U. 4. <b>--2</b> To immolate, sacrifice.</body><tail><L>26527</L><pc>0994-b</pc></tail></H1>
```

Is cologne  code somehow not using the expected ap90.sqlite ?

**Comment by funderburkjim** [comment]
## problem is in dictinfo

In adapting LRV, I made a change to how $dictyear is used in dictinfo.php (in csl-apidev).
This change was to permit the year for LRV dictionary to be 2022.

The change had the effect of using the 2014 data for ap90.sqlite!
Changing $dictyear to 2020 for ap90 in dictinfo.php solves the problem for ap90.

![image](https://user-images.githubusercontent.com/6393033/197938158-75108065-ae3d-4459-8c14-2cedd7288336.png)


I'll change the rest of $dictyear in a next session (when there is time to do checking).

**Comment by gasyoun** [comment]
> Changing $dictyear to 2020 for ap90 in dictinfo.php solves the problem for ap90.

Sometimes I do not understand how you manage to be so smart.

**Comment by funderburkjim** [comment]
The rest of $dictyear changed, seems to be ok. Perhaps others will also do some random checking.
Can now close issue.
