### ISSUE TITLE
Simple search for ABCH, ACPH and ACSJ

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-apidev#36]
Currently the HTMLs at https://www.sanskrit-lexicon.uni-koeln.de/scans/ACPHScan/2023/web/webtc2/index.php work fine

see 
![IMG_4979](https://github.com/sanskrit-lexicon/csl-apidev/assets/5755132/d9e2a7b5-6763-4917-82ec-8e369dd49995)

whereas the HTML at simple-search at gives the gender block with some glitch. 

![IMG_4980](https://github.com/sanskrit-lexicon/csl-apidev/assets/5755132/97964aad-9dcb-4c4d-9ebf-3edcdfa340de)

**Comment by drdhaval2785** [comment]
I think, this is because we have not made any changes to simple search display which we have made in regular display. @funderburkjim may be able to locate the missing part.

**Comment by funderburkjim** [comment]
It was an omission regarding getword_data.php.  
I think this now corrected.

<img width="686" alt="image" src="https://github.com/sanskrit-lexicon/csl-apidev/assets/6393033/decbaccd-5228-4795-b870-7c0401d42327">



( i pulled cs-apidev at cologne)
