### ISSUE TITLE
akarna bug in simple-search

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-apidev#37]
Noticed some failures in simple search.
For instance:
<img width="674" alt="image" src="https://github.com/sanskrit-lexicon/csl-apidev/assets/6393033/12ffddb8-4318-43b1-a3e1-5dec6fae14dd">

**Comment by drdhaval2785** [comment]
I dont know if it has any bearing or not.
I recently changed akarRA to akarRa in MW72 in commit https://github.com/sanskrit-lexicon/csl-orig/commit/33d92caeb03c720e1e0b7659871237225b2c38c0

**Comment by funderburkjim** [comment]
Yes, I noticed that.  Even when hwnorm1 was updated (and so include your changes to mw72),  the akarna bug remains.  So, I think the bug is unrelated to your mw72 corrections.

**Comment by funderburkjim** [comment]
This bug turns out to be related to  recent installation of ACPH kosha.

This kosha has the 'empty string' as a headword. We can see this with the list display:

<img width="758" alt="image" src="https://github.com/sanskrit-lexicon/csl-apidev/assets/6393033/a11df046-0602-4ee0-88d0-4ef4c46b44f1">

The 'empty' headword is (from acphw.txt)
 `<L>46<pc>4<k1><k2><ln1>504<ln2>509`
Here is the L=46 entry of [acph.txt](https://github.com/sanskrit-lexicon/csl-orig/blob/master/v02/acph/acph.txt) , which leads to the empty headword.
```
<L>46<pc>4
<info kvvv="<s>martyakARqaH</s>"/>
<eid>1245<syns>  <<<<<NO SYNS
<eid>1249<syns>
<s>apUpe pAriSAlo'Ta karambo daDisaktuzu (95) .</s>
<LEND>
```

**Comment by funderburkjim** [comment]
## bug solution

My solution was to get rid of the empty headword in hwnorm1.
See [this commit to hwnorm1](https://github.com/sanskrit-lexicon/hwnorm1/commit/ac530e)
Then the revised hwnorm1c.sqlite was moved, as usual, here in csl-apidev.

----------------------------------

I first tried to solve the problem by a revision to the [v1.1/simple-search.php](https://github.com/sanskrit-lexicon/csl-apidev/blob/master/simple-search/v1.1/simple_search.php).
But this attempt was not productive -- the logic here is subtle (read 'hard to revise!').

---------------------------------------------
@drdhaval2785  You *could* revise acph.txt in csl-orig to remove `L=46'. However,  as of now, I don't think such a revision is required.

**Comment by drdhaval2785** [comment]
I will revise acph.txt

**Comment by gasyoun** [comment]
@funderburkjim thanks for fixing. So it was @drdhaval2785 who broke the whole site down ))
