### ISSUE TITLE
Reorganizing listhier.php

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-apidev#5]
listhier.php is responsible for the 'list' part of the listview display of apidev;  this listview display is the one used in simple-search.

Formerly,  the code included a lot of 'top-level' php code and functions;  this not only cluttered up the global namespace of php, but also made it difficult to discern the interdependencies of the code.

The bulk of the code is now written as a php class (ListhierClass), and listhier.php itself is a simple usage of an instance of the class.  This is described below in more detail.

**Comment by funderburkjim** [comment]
## review of uses of listhier

When, as in simple search, listview.php retrieves information for a citation,  the list part of the listview display is done by listhier  [listhier == hierarchical list; this name given because of the
hierarchical arrangement (H1-H4) of the MW dictionary.]
listhier outputs the html of the list of headwords including the first homonym of *harika* and the entries around that first homonym.

![image](https://user-images.githubusercontent.com/6393033/62970422-72071680-bddd-11e9-91b0-5c4fbc47c93e.png)

If we click the arrow (yellow-shaded background to arrow) preceding the second homonym of *harika* , then listhier shows the headwords around this second homonym.

![image](https://user-images.githubusercontent.com/6393033/62970111-b7771400-bddc-11e9-9df8-fd2a5828934d.png)

If we click on one of the words, say *hartavya* in the list (first image above),  the entry for the word appears in the right pane.

![image](https://user-images.githubusercontent.com/6393033/62970643-f78ac680-bddd-11e9-9d38-b94c9035c040.png)

Finally, if we click on the up or down triangles of the list, then the list is recomputed using words preceding the first word of the list or following the last word of the list.  For instance, clicking down arrow of preceding display yields:

![image](https://user-images.githubusercontent.com/6393033/62970808-4df80500-bdde-11e9-8f37-76050635b752.png)

**Comment by funderburkjim** [comment]
## 'Naked' listhier

We can call listhier.php directly. for instance

![image](https://user-images.githubusercontent.com/6393033/62971106-fad28200-bdde-11e9-80d9-1e72167b428f.png)

But now clicking on any of the words or up/down arrows does nothing;  Because some required Javascript functions are external to listhier.

This shows that listhier's full utility is within the context of something like listview.php

**Comment by gasyoun** [comment]
> preceding the second homonym of harika

Is there a list of what combinations of red marked symbols can actually occur and what they mean?

**Comment by funderburkjim** [comment]
## listhier.php after refactoring
```
<?php
 require_once("listhierClass.php");
 function listhierCall() {
  $temp_listhier = new ListhierClass();
  $temp_table1 = $temp_listhier->table1;
  echo($temp_table1);
 }
 listhierCall();
?> 
```
This is very simple.  A function 'listhierCall' is defined, and then called.  

This function instantiates an instance of the *ListhierClass* class,  
retrieves a public variable 'table1' from the instance,
then sends this 'table1' to standard output  (i.e., back to the user's browser).

**Comment by funderburkjim** [comment]
## Brief description of the ListhierClass class

The constructor for this class is responsible for creating the string of html that is assigned to the value of public variable *table1*.   This construction takes about 400 lines of php code, involving 11 other functions.  The file involved is [listhierClass.php](https://github.com/sanskrit-lexicon/csl-apidev/blob/master/listhierClass.php).

Instead of input parameters, the constructor gathers inputs from PHP's global $_REQUEST  array, which gathers such information as the dictionary  (*&dict=mw*), headword (*&key=harika*), and so forth from the browser request.

It uses this information to gather headwords from the dictionary digitization (e.g. a Dal (data-access-layer) object connecting the program to mw.sqlite).  And converts these headwords into html with links to Javascript and css to display and provide functionality.

**Comment by funderburkjim** [comment]
> combinations of red marked symbols ?

No list of possibilities exists, yet.   See next for a first list.

## listhier decoration

The various *decorations* of the words in the list were made solely in the context of MW markup, so I doubt if these decorations appear with other dictionaries.

Here are many of these decorations:
* Initial red `.` (0,1,2 or 3 of these).   identifies the MW *line*.  0 periods means entry is an *H1* ,
   1 period means *H2*, etc.
* following red numeral (or lower-case letter).   This is a homonym.
   The numerical homonyms are part of the MW text.
   The alphabetical homonyms are ones assigned by Cologne digitization;  this assignment used
   an algorithm developed by Scharf and Pawan several years ago.
* (headword)  This indicates a 'B' or 'C'.   Look at 'hAra',  you'll see '(hArA)' and '(hArI)'
* red-word  = Supplement word;  green-word = Revision word
![image](https://user-images.githubusercontent.com/6393033/62984845-b6f17400-be02-11e9-9852-8505e5d49c7e.png)

The above are likely all the kinds of decorations.

**Comment by gasyoun** [comment]
> The various decorations of the words in the list were made solely in the context of MW markup, so I doubt if these decorations appear with other dictionaries.

Even if not yet, who knows what comes next.

> The alphabetical homonyms are ones assigned by Cologne digitization; this assignment used
an algorithm developed by Scharf and Pawan several years ago.

They were introduced, because...

> (headword) This indicates a 'B' or 'C'.

Missed what is said, sorry.

> The above are likely all the kinds of decorations.

Jim, mesmerizing. It will all become part of the documentation of web and part of my addition to a printed book on how to use MW. The book will come out in 2020-2021.
