### ISSUE TITLE
ID= overwriting

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-apidev#6]
In listview display of entries  (e.g. in simple-search which uses listview display),  there is special handling of the `[ID=...]` Cologne record identifier.   By *special*, I mean that it differs from the normal Basic Display.

The ID is placed at the end of an entry.
This special handling sometimes results in overwriting when the last line of the entry is 'indented'  by using CSS 'relative' positioning.  Here is an instance of the bug:

![image](https://user-images.githubusercontent.com/6393033/63192205-8bf06580-c038-11e9-96ba-b9e54b258275.png)

**Comment by funderburkjim** [comment]
One solution that seems to work is to add extra spaces (using the non-breaking space character expressed as the html entity `&nbsp;`) before the `[ID=xxx]` data.

This special handling is done in dispitem.php, and is only done for a list of dictionaries where the adjustment may be needed (i.e., in the dictonaries that sometimes use relative positioning).  The relative positioning is done in 'basicdisplay.php'.  

To solve the problem shown above for PW dictionary,  it was only necessary to add 'PW' to the list (in dispitem.php) of dictionaries needing extra space:
```
  if (in_array($this->dictup,['GRA','STC','AP','AP90','PWG','BUR','PW'])) {
   // Add extra spaces so preceding text will not be overwritten.
   // This applies to dictionaries where a 'position:relative' css style 
   // is used to indent text.
   $lnumshow = "<span class='lnum' '> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;[<span title='Cologne record ID'>ID=</span>$lnum]</span>";
  }else {
   $lnumshow = "<span class='lnum'> [<span title='Cologne record ID'>ID=</span>$lnum]</span>";
  }
```
![image](https://user-images.githubusercontent.com/6393033/63192791-ee963100-c039-11e9-8461-eac1339aee93.png)

**Comment by funderburkjim** [comment]
## How Basic Display differs

Notice the difference in the way Basic Display shows the ID.

![image](https://user-images.githubusercontent.com/6393033/63192963-50ef3180-c03a-11e9-8ead-45aefbc2d0eb.png)

**Comment by gasyoun** [comment]
It's time we hide the ID from view.

**Comment by funderburkjim** [comment]
For a casual user, such as a student just starting Sanskrit, the ID is not helpful.  There are also probably other parts of the display that may be unhelpful.

But for some other users, such as those who submit corrections,  the ID is important, as it aids in the precise communication about what place in a dictionary is under discussion.

So there are pros and cons for the ID.

Maybe some dictionaries (e.g. MW) need displays that might be termed *student editions*.

**Comment by gasyoun** [comment]
> For a casual user, such as a student just starting Sanskrit, the ID is not helpful. There are also probably other parts of the display that may be unhelpful.

Yes

> But for some other users, such as those who submit corrections, the ID is important, as it aids in the precise communication about what place in a dictionary is under discussion..

The Javascript that we have tested can handle it. No need to show it. The script can grab it from the code itself.

> So there are pros and cons for the ID.

ID is a database question. Nobody should care about them. It's a question of coding and can be handled without showing them.

> Maybe some dictionaries (e.g. MW) need displays that might be termed student editions.

Guess, no. But intro will not hurt for sure. I will get there.
