### ISSUE TITLE
Reorganizing servepdf.php

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-apidev#7]
All of the php code in apidev is object oriented  (i.e. uses PHP classes) .

The one exception currently is 'servepdf.php'.   

This needs to be refactored into an object oriented form also.

**Comment by gasyoun** [comment]
> object oriented

Guess it what was you where working on for the last weeks, hurray.

**Comment by funderburkjim** [comment]
The contemplated enhancements are now in place.  
The program modules involved are:
* servepdf.php,  now refactored into
  * [servepdf.php](https://github.com/sanskrit-lexicon/csl-apidev/blob/master/servepdf.php) : a simple interface to the ServepdfClass.
  * [servepdfClass.php](https://github.com/sanskrit-lexicon/csl-apidev/blob/master/servepdfClass.php) - the constructor contains logic to generate html that servepdfCall sends back to browser.
* [dictinfo.php](https://github.com/sanskrit-lexicon/csl-apidev/blob/master/dictinfo.php) now has a *get_pdfpages_url()* method that chooses the URL that 'contains' the scanned image.

These changes make the code functionally consistent with the servepdf.php code used by the displays (Basic, List, etc.) for the individual dictionaries.  See https://github.com/sanskrit-lexicon/csl-websanlexicon/issues/6 for a detailed discussion of this functionality.

In brief, the enhancements:
* permit easier management of the location of the scanned image files
* Allow display of the pdf image files on Android-based devices, and on Ipad devices.
