### ISSUE TITLE
dokuwiki documentation of api endpoints

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-apidev#8]
See https://www.sanskrit-lexicon.uni-koeln.de/doc/dokuwiki/doku.php?id=scans:apidev.

This contains fairly complete documentation of the Restful endpoints for the apidev code.

The other non-endpoint PHP modules remain to be documented.

**Comment by gasyoun** [comment]
> getsuggest  return short list of words with a certain prefix

Only prefix or suffixes as well?

**Comment by funderburkjim** [comment]
prefix only.

**Comment by gasyoun** [comment]
> prefix only.

So it's not equal to Advanced search functionality. But should/could?

**Comment by funderburkjim** [comment]
@gasyoun  Maybe you should open an 'enhancement' issue regarding suffix functionality.  Generally, searching by other than prefix requires quite different techniques behind the scenes.

**Comment by drdhaval2785** [comment]
Docuwiki is now gone. Can we close this @funderburkjim ?

**Comment by funderburkjim** [comment]
Docuwiki is now gone ---
The way I used docuwiki led to security breaches  (someone posted several gigs of garbagey data).


 agree this can be closed, and am closing.
