### ISSUE TITLE
dictinfowhich revised

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-apidev#9]
Cologne is planning to migrate the sanskrit-lexicon website to another file system, probably on Sep 20.  

This should be completely transparent to sanskrit-lexicon website users (i.e., no down time).

However, one detail is that the file-system path names will be changed.

There is some logic in apidev  (as well as the basic, etc. displays)  which takes slightly different
actions depending on whether the code thinks it is running at Cologne or somewhere else.
This determination is made by a simple test in dictinfowhich.php , and this test was modified today so it should work both now and after migration to new file system.
```
 if (preg_match("|^/[an]fs/|",dirname(__DIR__))) {
  $dictinfowhich = "cologne"; 
 }else {
  $dictinfowhich = "xampp";
}
```

A similar change was made in the web/webtc/dictinfowhich.php module used in the Basic, etc. displays.

**Comment by gasyoun** [comment]
> so it should work both now and after migration to new file system.

So let us wait?

**Comment by drdhaval2785** [comment]
I think the migration was made and there is no need to keep it open now. Closing. If needed, issue can be reopened.

**Comment by funderburkjim** [comment]
Agree with closing.
